### ISSUE TITLE
New Vendor Order Management System

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#626]
**Overview**

This proposal will outline the requirements for the new vendor order management system. Currently, vendors access order information via the commission's table. This has several limitations which include the following 

- No order status management for vendors
- No way to manage shipping details easily 
- Limited order management capabilities 

The new vendor order management system would provide a new order view for vendors. They would have total control over their orders independent of the parent order. The parent order is what the admin and customers see. 

Vendor capabilities for the new order management 

- [ ] View order details (including items, product price and commission earned, taxes and shipping)
- [ ] Change order status 
- [ ] Mark Shipped
- [ ] Add shipping tracking number 

Admins will be able to view the following details of the orders 
- [ ] Vendor orders details will be shown on the WooCommerce > Order edit page 
- [ ] Vendor order status will be shown on the WooCommerce > Order edit page 
- [ ] Vendor order tracking number will be shown on the WooCommerce > Order edit page 

**Tasks**

- [ ] Add Vendors order management screen for marketplace admin on the WooCommerce > Order page 
- [ ] New vendor order will only include relevant data to the particular vendor. No data duplication from the parent order is to happen. Anything related to the customer will be retrieved from the parent order.
- [ ] Replace the existing orders page in WordPress admin with a new Orders page. 
- [ ] New order dashboard page to view and manage orders for the vendor role user this will look like a cut-down version of the WooCommerce > Order page  
- [ ] Add tools to migrate/update order data for old versions.
