### ISSUE TITLE
Updated Vendor Frontend Dashboard 

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#628]
**Overview**

The new dashboard will consolidate our existing 2 dashboard system into a single dashboard. The free dashboard will have limited features that can be easily extended in pro or 3rd party plugins.

**Describe the solution you'd like**
The new dashboard will consolidate the simple dashboard currently in use and integrate the dashboard from WC Vendors Pro. 

The dashboard will use arrays to define the various forms and form fields so they can be easily controlled in the WC Vendors settings page, vendor user edit page and the form itself from a single set of definitions. 

**Tasks**

- [ ] Migrate the form helper and dashboard system from wc vendors pro 
- [ ] Features available to vendors in free dashboard
- [ ] Dashboard page
   - [ ] Total sales / Total Earnings / Total Orders
- [ ] Product Table Page
   - [ ] List products, search products, actions ( edit, duplicate, delete, view )
   - [ ] Product Edit ( Simple, Group, External )
- [ ] Orders Table Page
  - [ ] List orders, search orders, actions ( view, mark shipped, change status )
- [ ] Settings page
  - [ ] Shop name, shop description, seller description, shop icon, shop banner, address, payment details
