### ISSUE TITLE
Vendors Page 

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#629]
**Overview**
Create a dedicated page for vendor management instead of via the user's page. This page is a new vendor management page which will list all vendors and allow you to do the following. 

- Add / Remove vendors 
- Approve / Deny vendors 
- Enable or disable a vendor 
- Edit vendor and all related settings/capabilities 

**Describe the solution you'd like**
Clean vendor page and vendor edit page to easily manage vendors from the WordPress Admin. 

**Tasks** 

- [X] Add new Vendors Page Under WC Vendors > Vendors 
- [ ] Vendor list table will have the following columns (all/vendors/pending)
	- [ ] Username (actions column [Edit|delete])
	- [ ] Shop Name
	- [ ] email address 
	- [ ] role
	- [ ] enabled (slide toggle)
	- [ ] bulk actions (deny, approve, delete, disable, enable)
	- [ ] search box (username, shop name, email) 
- [ ] Edit vendor screen provides a single interface to edit everything related to the vendor, settings, capabilities, commission overrides
