### ISSUE TITLE
Migrate Settings 

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#631]
**Overview**
Migrate all existing settings from 2.0 to 3.0. 

**Describe the solution you'd like**
All existing settings should be moved across. 

**Tasks** 

- [x] Migrate the following tabs 
	- [x] General 
		- [ ] Marketplace options 
	- [ ] Commission
	- [ ] Capabilities
	- [ ] Display
		- [ ] General
		- [ ] Store settings (new, moved from general tab
		- [ ] Labels 
		- [ ] Advanced
	- [ ] Advanced 
- [ ] Remove Payments tab

**Stores Settings** 

There will be a new tab added under display settings which will control how vendor stores are output. A new option will be added to enable/disable stores completely. 
- [ ] Enable Vendor Storefronts (this will enable the vendor storefronts, checked by default)
