### ISSUE TITLE
The SEO meta title is outputting twice

### ISSUE THREAD

**Issue by Mrlunsuper** [wcvendors/wcvendors#773]
**Describe the bug**

**To Reproduce**
1. Log in as a vendor
2. Go to Store Settings
3. Go to tab SEO and fill the SEO title field then save your settings
4. Back to dashboard and click View Store
5. In google chrome right click and choose Inspect in the context menu. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/29702044/123503540-bde3a180-d67d-11eb-8564-527d27e6ac00.png)

**Expected behavior**
The SEO meta title shouldn't output twice

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
